#pragma once

#define TOP_BAR_RECT_ANCHORS {{0, 0}, {1, 0.15}}
#define TOP_BAR_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define TOP_BAR_RECT_RELATIVE_POSITION {0, 0}
#define TOP_BAR_RECT_SIZE {0, 100}

#define TITLE_RECT_ANCHORS ANCHORS_MIDDLE_STRETCH
#define TITLE_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define TITLE_RECT_RELATIVE_POSITION {0, 0}
#define TITLE_RECT_SIZE {0, 0}

#define RELOAD_BUTTON_RECT_ANCHORS ANCHORS_MIDDLE_LEFT
#define RELOAD_BUTTON_RECT_PIVOT PIVOT_MIDDLE_LEFT
#define RELOAD_BUTTON_RECT_RELATIVE_POSITION {50, 0}
#define RELOAD_BUTTON_RECT_SIZE {50, 50}

#define DEVICES_RECYCLE_VIEW_RECT_ANCHORS {{0.1, 0.15}, {0.9, 1}}
#define DEVICES_RECYCLE_VIEW_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define DEVICES_RECYCLE_VIEW_RECT_RELATIVE_POSITION {0, 0}
#define DEVICES_RECYCLE_VIEW_RECT_SIZE {0, 0}

#define DEVICES_RECYCLE_VIEW_VIEWS_PER_ROW 4
#define DEVICES_RECYCLE_VIEW_HORIZONTAL_MARGIN 0.05
#define DEVICES_RECYCLE_VIEW_VERTICAL_MARGIN 0.05
#define DEVICES_RECYCLE_VIEW_MARGINS {DEVICES_RECYCLE_VIEW_HORIZONTAL_MARGIN, DEVICES_RECYCLE_VIEW_VERTICAL_MARGIN}
#define DEVICES_RECYCLE_VIEW_ROW_HEIGHT 150
#define DEVICES_RECYCLE_VIEW_BUFFER_ROWS 2
