#pragma once

#pragma region Top Bar

#define TOP_BAR_RECT_ANCHORS {{0, 0}, {1, 0.15}}
#define TOP_BAR_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define TOP_BAR_RECT_RELATIVE_POSITION {0, 0}
#define TOP_BAR_RECT_SIZE {0, 0}

#define TITLE_RECT_ANCHORS ANCHORS_MIDDLE_STRETCH
#define TITLE_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define TITLE_RECT_RELATIVE_POSITION {0, 0}
#define TITLE_RECT_SIZE {0, 0}

#define BACK_BUTTON_RECT_ANCHORS ANCHORS_MIDDLE_LEFT
#define BACK_BUTTON_RECT_PIVOT PIVOT_MIDDLE_LEFT
#define BACK_BUTTON_RECT_RELATIVE_POSITION {50, 0}
#define BACK_BUTTON_RECT_SIZE {50, 50}

#pragma endregion

#pragma region Current Profile

#define CURRENT_PROFILE_RECT_ANCHORS {{0, 0.15}, {1, 0.35}}
#define CURRENT_PROFILE_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define CURRENT_PROFILE_RECT_RELATIVE_POSITION {0, 0}
#define CURRENT_PROFILE_RECT_SIZE {0, 0}

#define CURRENT_PROFILE_TITLE_RECT_ANCHORS {{0, 0}, {1, 0.4}}
#define CURRENT_PROFILE_TITLE_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define CURRENT_PROFILE_TITLE_RECT_RELATIVE_POSITION {0, 0}
#define CURRENT_PROFILE_TITLE_RECT_SIZE {0, 0}

#define CURRENT_PROFILE_NAME_RECT_ANCHORS {{0, 0.4}, {1, 0.7}}
#define CURRENT_PROFILE_NAME_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define CURRENT_PROFILE_NAME_RECT_RELATIVE_POSITION {0, 0}
#define CURRENT_PROFILE_NAME_RECT_SIZE {0, 0}

#define CURRENT_PROFILE_BUTTONS_RECT_ANCHORS {{0, 0.7}, {1, 1}}
#define CURRENT_PROFILE_BUTTONS_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define CURRENT_PROFILE_BUTTONS_RECT_RELATIVE_POSITION {0, 0}
#define CURRENT_PROFILE_BUTTONS_RECT_SIZE {0, 0}

#define CURRENT_PROFILE_EDIT_BUTTON_RECT_ANCHORS {{0.45, 0.5}, {0.45, 0.5}}
#define CURRENT_PROFILE_EDIT_BUTTON_RECT_PIVOT PIVOT_MIDDLE_RIGHT
#define CURRENT_PROFILE_EDIT_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define CURRENT_PROFILE_EDIT_BUTTON_RECT_SIZE {50, 50}

#define CURRENT_PROFILE_UNLOAD_BUTTON_RECT_ANCHORS {{0.55, 0.5}, {0.55, 0.5}}
#define CURRENT_PROFILE_UNLOAD_BUTTON_RECT_PIVOT PIVOT_MIDDLE_LEFT
#define CURRENT_PROFILE_UNLOAD_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define CURRENT_PROFILE_UNLOAD_BUTTON_RECT_SIZE {50, 50}

#pragma endregion

#pragma region Profile Recycle View

#define PROFILE_RECYCLE_VIEW_RECT_ANCHORS_EXPANDED {{0.1, 0.15}, {0.9, 1}}
#define PROFILE_RECYCLE_VIEW_RECT_ANCHORS_SHRANK {{0.1, 0.35}, {0.9, 1}}
#define PROFILE_RECYCLE_VIEW_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define PROFILE_RECYCLE_VIEW_RECT_RELATIVE_POSITION {0, 0}
#define PROFILE_RECYCLE_VIEW_RECT_SIZE {0, 0}

#define PROFILE_RECYCLE_VIEW_VIEWS_PER_ROW 4
#define PROFILE_RECYCLE_VIEW_HORIZONTAL_PADDING 0.1
#define PROFILE_RECYCLE_VIEW_VERTICAL_PADDING 0.1
#define PROFILE_RECYCLE_VIEW_PADDINGS {PROFILE_RECYCLE_VIEW_HORIZONTAL_PADDING, PROFILE_RECYCLE_VIEW_VERTICAL_PADDING}
#define PROFILE_RECYCLE_VIEW_ROW_HEIGHT 150
#define PROFILE_RECYCLE_VIEW_BUFFER_ROWS 2

#pragma endregion