#pragma once

#pragma region Top Bar

#define TOP_BAR_RECT_ANCHORS {{0, 0}, {1, 0.15}}
#define TOP_BAR_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define TOP_BAR_RECT_RELATIVE_POSITION {0, 0}
#define TOP_BAR_RECT_SIZE {0, 100}

#define TITLE_RECT_ANCHORS ANCHORS_MIDDLE_STRETCH
#define TITLE_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define TITLE_RECT_RELATIVE_POSITION {0, 0}
#define TITLE_RECT_SIZE {0, 0}

#define BACK_BUTTON_RECT_ANCHORS ANCHORS_MIDDLE_LEFT
#define BACK_BUTTON_RECT_PIVOT PIVOT_MIDDLE_LEFT
#define BACK_BUTTON_RECT_RELATIVE_POSITION {50, 0}
#define BACK_BUTTON_RECT_SIZE {50, 50}

#pragma endregion

#pragma region Profile Name

#define PROFILE_NAME_RECT_ANCHORS {{0.4, 0.2}, {0.6, 0.2}}
#define PROFILE_NAME_RECT_PIVOT PIVOT_TOP_CENTER
#define PROFILE_NAME_RECT_RELATIVE_POSITION {0, 0}
#define PROFILE_NAME_RECT_SIZE {0, 50}

#pragma endregion

#pragma region Profile Buttons

#define PROFILE_BUTTONS_RECT_ANCHORS {{0, 0.3}, {1, 0.3}}
#define PROFILE_BUTTONS_RECT_PIVOT PIVOT_TOP_CENTER
#define PROFILE_BUTTONS_RECT_RELATIVE_POSITION {0, 0}
#define PROFILE_BUTTONS_RECT_SIZE {0, 50}

#define PROFILE_LOAD_UNLOAD_BUTTON_RECT_ANCHORS {{0.3, 0}, {0.45, 1}}
#define PROFILE_LOAD_UNLOAD_BUTTON_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define PROFILE_LOAD_UNLOAD_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define PROFILE_LOAD_UNLOAD_BUTTON_RECT_SIZE {0, 0}

#define PROFILE_LINK_BUTTON_RECT_ANCHORS {{0.55, 0}, {0.7, 1}}
#define PROFILE_LINK_BUTTON_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define PROFILE_LINK_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define PROFILE_LINK_BUTTON_RECT_SIZE {0, 0}

#pragma endregion

#pragma region SubProfile

#define SUB_PROFILE_RECT_ANCHORS {{0, 0.4}, {0.2, 1}}
#define SUB_PROFILE_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define SUB_PROFILE_RECT_RELATIVE_POSITION {0, 0}
#define SUB_PROFILE_RECT_SIZE {0, 0}

#define SUB_PROFILE_TITLE_RECT_ANCHORS {{0, 0}, {1, 0}}
#define SUB_PROFILE_TITLE_RECT_PIVOT PIVOT_TOP_CENTER
#define SUB_PROFILE_TITLE_RECT_RELATIVE_POSITION {0, 0}
#define SUB_PROFILE_TITLE_RECT_SIZE {0, 70}

#define SUB_PROFILE_LIST_RECT_ANCHORS {{0, 0.2}, {1, 1}}
#define SUB_PROFILE_LIST_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define SUB_PROFILE_LIST_RECT_RELATIVE_POSITION {0, 0}
#define SUB_PROFILE_LIST_RECT_SIZE {0, 0}

#define SUB_PROFILE_RECYCLE_VIEW_VIEWS_PER_ROW 1
#define SUB_PROFILE_RECYCLE_VIEW_HORIZONTAL_PADDING 0
#define SUB_PROFILE_RECYCLE_VIEW_VERTICAL_PADDING 0
#define SUB_PROFILE_RECYCLE_VIEW_PADDINGS {SUB_PROFILE_RECYCLE_VIEW_HORIZONTAL_PADDING, SUB_PROFILE_RECYCLE_VIEW_VERTICAL_PADDING}
#define SUB_PROFILE_RECYCLE_VIEW_ROW_HEIGHT 50
#define SUB_PROFILE_RECYCLE_VIEW_BUFFER_ROWS 2

#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_SUB_PROFILE_EDIT_BUTTON_RECT_ANCHORS {{0, 0}, {0.8, 1}}
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_SUB_PROFILE_EDIT_BUTTON_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_SUB_PROFILE_EDIT_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_SUB_PROFILE_EDIT_BUTTON_RECT_SIZE {0, 0}

#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_SUB_PROFILE_DELETE_BUTTON_RECT_ANCHORS {{0.8, 0}, {1, 1}}
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_SUB_PROFILE_DELETE_BUTTON_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_SUB_PROFILE_DELETE_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_SUB_PROFILE_DELETE_BUTTON_RECT_SIZE {0, 0}

#pragma endregion

#pragma region Input

#define INPUT_RECT_ANCHORS {{0.2, 0.4}, {0.5, 1}}
#define INPUT_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define INPUT_RECT_RELATIVE_POSITION {0, 0}
#define INPUT_RECT_SIZE {0, 0}

#define INPUT_TITLE_RECT_ANCHORS {{0, 0}, {1, 0}}
#define INPUT_TITLE_RECT_PIVOT PIVOT_TOP_CENTER
#define INPUT_TITLE_RECT_RELATIVE_POSITION {0, 0}
#define INPUT_TITLE_RECT_SIZE {0, 70}

#define INPUT_BUTTONS_RECT_ANCHORS {{0, 0.2}, {1, 0.2}}
#define INPUT_BUTTONS_RECT_PIVOT PIVOT_TOP_CENTER
#define INPUT_BUTTONS_RECT_RELATIVE_POSITION {0, 0}
#define INPUT_BUTTONS_RECT_SIZE {0, 0}

#define INPUT_RECORD_BUTTON_RECT_ANCHORS {{0.05, 0}, {0.45, 0}}
#define INPUT_RECORD_BUTTON_RECT_PIVOT PIVOT_TOP_CENTER
#define INPUT_RECORD_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define INPUT_RECORD_BUTTON_RECT_SIZE {0, 50}

#define INPUT_DELETE_BUTTON_RECT_ANCHORS {{0.55, 0}, {0.95, 0}}
#define INPUT_DELETE_BUTTON_RECT_PIVOT PIVOT_TOP_CENTER
#define INPUT_DELETE_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define INPUT_DELETE_BUTTON_RECT_SIZE {0, 50}

#define INPUT_LIST_RECT_ANCHORS {{0, 0.4}, {1, 1}}
#define INPUT_LIST_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define INPUT_LIST_RECT_RELATIVE_POSITION {0, 0}
#define INPUT_LIST_RECT_SIZE {0, 0}

#define INPUT_RECYCLE_VIEW_VIEWS_PER_ROW 1
#define INPUT_RECYCLE_VIEW_HORIZONTAL_PADDING 0
#define INPUT_RECYCLE_VIEW_VERTICAL_PADDING 0
#define INPUT_RECYCLE_VIEW_PADDINGS {SUB_PROFILE_RECYCLE_VIEW_HORIZONTAL_PADDING, SUB_PROFILE_RECYCLE_VIEW_VERTICAL_PADDING}
#define INPUT_RECYCLE_VIEW_ROW_HEIGHT 50
#define INPUT_RECYCLE_VIEW_BUFFER_ROWS 2

#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_INPUT_EDIT_BUTTON_RECT_ANCHORS {{0, 0}, {0.8, 1}}
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_INPUT_EDIT_BUTTON_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_INPUT_EDIT_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_INPUT_EDIT_BUTTON_RECT_SIZE {0, 0}

#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_INPUT_DELETE_BUTTON_RECT_ANCHORS {{0.8, 0}, {1, 1}}
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_INPUT_DELETE_BUTTON_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_INPUT_DELETE_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define SUB_PROFILE_RECYCLE_VIEW_DEFAULT_INPUT_DELETE_BUTTON_RECT_SIZE {0, 0}

#pragma endregion

#pragma region Output

#define OUTPUT_RECT_ANCHORS {{0.5, 0.4}, {1, 1}}
#define OUTPUT_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define OUTPUT_RECT_RELATIVE_POSITION {0, 0}
#define OUTPUT_RECT_SIZE {0, 0}

#define OUTPUT_TITLE_RECT_ANCHORS {{0, 0}, {1, 0}}
#define OUTPUT_TITLE_RECT_PIVOT PIVOT_TOP_CENTER
#define OUTPUT_TITLE_RECT_RELATIVE_POSITION {0, 0}
#define OUTPUT_TITLE_RECT_SIZE {0, 70}

#define OUTPUT_TYPE_RECT_ANCHORS {{0, 0.2}, {0.3, 1}}
#define OUTPUT_TYPE_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define OUTPUT_TYPE_RECT_RELATIVE_POSITION {0, 0}
#define OUTPUT_TYPE_RECT_SIZE {0, 0}

#define OUTPUT_EMIT_INPUT_EVENT_COMMAND_BUTTON_RECT_ANCHORS {{0, 0}, {1, 0.25}}
#define OUTPUT_EMIT_INPUT_EVENT_COMMAND_BUTTON_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define OUTPUT_EMIT_INPUT_EVENT_COMMAND_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define OUTPUT_EMIT_INPUT_EVENT_COMMAND_BUTTON_RECT_SIZE {0, 0}

#define OUTPUT_MACRO_COMMAND_BUTTON_RECT_ANCHORS {{0, 0.25}, {1, 0.50}}
#define OUTPUT_MACRO_COMMAND_BUTTON_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define OUTPUT_MACRO_COMMAND_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define OUTPUT_MACRO_COMMAND_BUTTON_RECT_SIZE {0, 0}

#define OUTPUT_SWITCH_TO_SUB_PROFILE_COMMAND_BUTTON_RECT_ANCHORS {{0, 0.50}, {1, 0.75}}
#define OUTPUT_SWITCH_TO_SUB_PROFILE_COMMAND_BUTTON_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define OUTPUT_SWITCH_TO_SUB_PROFILE_COMMAND_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define OUTPUT_SWITCH_TO_SUB_PROFILE_COMMAND_BUTTON_RECT_SIZE {0, 0}

#define OUTPUT_SHUTDOWN_APPLICATION_COMMAND_BUTTON_RECT_ANCHORS {{0, 0.75}, {1, 1}}
#define OUTPUT_SHUTDOWN_APPLICATION_COMMAND_BUTTON_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define OUTPUT_SHUTDOWN_APPLICATION_COMMAND_BUTTON_RECT_RELATIVE_POSITION {0, 0}
#define OUTPUT_SHUTDOWN_APPLICATION_COMMAND_BUTTON_RECT_SIZE {0, 0}

#define OUTPUT_TYPE_DETAILS_RECT_ANCHORS {{0.3, 0.2}, {1, 1}}
#define OUTPUT_TYPE_DETAILS_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define OUTPUT_TYPE_DETAILS_RECT_RELATIVE_POSITION {0, 0}
#define OUTPUT_TYPE_DETAILS_RECT_SIZE {0, 0}

#define OUTPUT_TYPE_DETAILS_INPUT_TEXT_BOX_RECT_ANCHORS {{0.05, 0.05}, {0.95, 0.2}}
#define OUTPUT_TYPE_DETAILS_INPUT_TEXT_BOX_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define OUTPUT_TYPE_DETAILS_INPUT_TEXT_BOX_RECT_RELATIVE_POSITION {0, 0}
#define OUTPUT_TYPE_DETAILS_INPUT_TEXT_BOX_RECT_SIZE {0, 0}

#define OUTPUT_TYPE_DETAILS_INPUT_DISPLAY_TEXT_BOX_RECT_ANCHORS {{0.05, 0.3}, {0.95, 0.95}}
#define OUTPUT_TYPE_DETAILS_INPUT_DISPLAY_TEXT_BOX_RECT_PIVOT PIVOT_MIDDLE_CENTER
#define OUTPUT_TYPE_DETAILS_INPUT_DISPLAY_TEXT_BOX_RECT_RELATIVE_POSITION {0, 0}
#define OUTPUT_TYPE_DETAILS_INPUT_DISPLAY_TEXT_BOX_RECT_SIZE {0, 0}

#define INPUT_DISPLAY_TEXT_BOX_COLOR ImColor{0.7f, 0.7f, 0.7f, 1.f}

#define LIST_OF_SUB_PROFILES_RECYCLE_VIEW_VIEWS_PER_ROW 1
#define LIST_OF_SUB_PROFILES_RECYCLE_VIEW_HORIZONTAL_PADDING 0
#define LIST_OF_SUB_PROFILES_RECYCLE_VIEW_VERTICAL_PADDING 0
#define LIST_OF_SUB_PROFILES_RECYCLE_VIEW_PADDINGS {LIST_OF_SUB_PROFILES_RECYCLE_VIEW_HORIZONTAL_PADDING, LIST_OF_SUB_PROFILES_RECYCLE_VIEW_VERTICAL_PADDING}
#define LIST_OF_SUB_PROFILES_RECYCLE_VIEW_ROW_HEIGHT 50
#define LIST_OF_SUB_PROFILES_RECYCLE_VIEW_BUFFER_ROWS 2

#pragma endregion